version: '3.8'
services:
  db-employee:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_DATABASE=employee
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
  employee-service:
    image: 'inse1n/employee-service'
    restart: always
    container_name: employee-service
    environment:
      - DB_HOSTNAME=db-employee
      - DB_PORT=3306
      - DB_NAME=employee
      - DB_USR=root
      - DB_PSW=root
      - EUREKA=eureka-service
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - HOSTNAME=config-service
    ports:
      - 8082:8082
    depends_on:
      - db-employee      
  gateway-service:
    image: 'inse1n/gateway-service'
    restart: always
    container_name: gateway-service
    environment:
      - EUREKA=eureka-service
      - HOSTNAME=config-service
      - eureka.client.serviceUrl.defaultZone=http://eureka-service:8761/eureka
      - spring.cloud.config.uri=http://config-service:8081
      - spring.config.import=optional:configserver:http://config-service:8081
    ports:
      - 8080:8080
    expose:
      - "8080"
    depends_on:
      - employee-service

  # db-marcas_reloj:
  #   image: 'mysql'
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=marcas_reloj
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_PASSWORD=root
  #   ports:
  #     - 3307:3306
  # db-justificative:
  #   image: 'mysql'
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=justificative
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_PASSWORD=root
  #   ports:
  #     - 3308:3306
  # db-extra_hours:
  #   image: 'mysql'
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=extra_hours
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_PASSWORD=root
  #   ports:
  #     - 3309:3306
  # db-planilla_sueldos:
  #   image: 'mysql'
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=planilla_sueldos
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_PASSWORD=root
  #   ports:
  #     - 3310:3306
networks:
  default:
    name: my-net
    external: true