server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**
        - id: timestamp-service
          uri: lb://timestamp-service
          predicates:
            - Path=/timestamp/**
        - id: justificative-service
          uri: lb://justificative-service
          predicates:
            - Path=/justificatives/**
        - id: extra-hours-service
          uri: lb://extra-hours-service
          predicates:
            - Path=/extra-hours/**
        - id: planilla-sueldos-service
          uri: lb://planilla-sueldos-service
          predicates:
            - Path=/planilla-sueldos/**             