server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: git@github.com:nic0/Mueblestgo_microservices.git
          search-paths: config-data
  application:
    name: config-service
